### ISSUE TITLE
This Hello World fails

### ISSUE THREAD

**Issue by rdebath** [nigelnquande/bf2c#1]
This should print "Hello World!".

``` bf
>++++++++[-<+++++++++>]<.>[][<-]>+>-[+]++>++>+++[>[->+++<<+++>]<<]>-----.
>->+++..+++.>-.<<+[>[+>+]>>]<--------------.>>.+++.------.--------.>+.>+.
```

**Comment by nigelnquande** [comment]
I have checked the BF code with beef. Indeed, the output is "Hello World!"

On inputting that code to the program, I found that it did not reserve enough space for the translation and caused a segfault (arrayIndexOutOfBounds). I have therefore changed the calculation to reserve more space for the translation. You might need to increase the value defined for `TRANSLATION_EXPANDER` if you encounter a segfault.

**Comment by rdebath** [comment]
Yes, I noticed the overflow; it's mainly triggered by the fact you've forgotten to add the length of the initial C heading code to your total. BTW if you want to shrink the size of the C code you could do something like this:

``` c
#include<unistd.h>
#define b while(*m) {
#define i read(0,m,1);
#define o write(1,m,1);
#define d --*m;
#define u ++*m;
#define l m-=1;
#define r m+=1;
#define e }
#define _ return 0;}
char mem[1048576];int main(){register char*m=mem;
r u u u u u u u u b d l u u u u u u u u u r e l o r b e b l d e r u r d
b u e u u r u u r u u u b r b d r u u u l l u u u r e l l e r d d d d d
o r d r u u u o o u u u o r d o l l u b r b u r u e r r e l d d d d d d
d d d d d d d d o r r o u u u o d d d d d d o d d d d d d d d o r u o r
u o _
```

**Comment by nigelnquande** [comment]
I'd like to keep my C code at least somewhat readable; shrinking it as you suggest doesn't leave it understandable to me. (My C knowledge is quite limited at best.)

Unless there's anything else I need to do to provide a better solution to the problem, I'm going to close this issue if the program manages to run your `bitwidth` test without encountering the same problem.

**Comment by rdebath** [comment]
But it is readable, it's just like the original source ... :smiling_imp: 

Seriously, though it's your project you should build it as you want to. Like many BF interpreters I expect you're using this to learn a real language or technique. So I'll give suggestions or hints ...

For example, you seem to be having issues with the dynamic allocation in C. Important things to remember are that you need an extra byte of space for the NUL byte (`'\0'`) at the end of any normal string and you must remember to copy or add it to the string. Also I wouldn't usually try to guess how long the converted string is going to be; I'd probably use `realloc()` to add more space when the string space is getting a bit tight. (But not counting exactly though, as realloc() can also be used to trim the leftover space when you're done).

**Comment by nigelnquande** [comment]
Thanks for the suggestion. I'll look into that if I ever actually write more BF*K code with which to test it (when I have nothing better to do and a day or two to kill). I don't think that will happen any time soon, though.
